config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'homes/top'
  root to: "homes#top"
  
  resources :books, only: [:new, :create, :edit, :update, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end 
  resources :users, only: [:show, :index, :edit, :update]
  
  
  
  get '/home/about' => "homes#about", as:'about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  
  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images3/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  
  validates_uniqueness_of :book_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  has_one_attached :profile_image
  
  validates :name, uniqueness: true, length: { minimum: 2, maximum: 20 }
  validates :introduction, length: { maximum: 50 }
  
  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    comment = current_user.book_comments.new(book_comment_params)
    comment.book_id = book.id
    comment.save
    redirect_to book_path(book.id)
  end
  
  def destroy
    BookComment.find(params[:id]).destroy
    redirect_to book_path(params[:book_id])
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @user = current_user
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book2 = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "Book was successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def is_matching_login_user
    @book = Book.find(params[:id])
    unless @book.user.id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_to request.referer
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end 
  
  def about
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def index
    @users = User.all
    @book = Book.new
    @user = current_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "You have updated user successfully."
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user_id = params[:id].to_i
    unless user_id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2>User info</h2>
  <%= image_tag user.get_profile_image(100,100) %>
  
  <table class="table">
    <tbody>
      <tr>
        <th>name</th>
        <th><%= user.name %></th>
      </tr>
      <tr>
        <th>introduction</th>
        <th><%= user.introduction %></th>
      </tr>
    </tbody>
  </table>
  
  
    <p>
      <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
      <i class="fas fa-user-cog"></i>
      <% end %>
    </p>
    
  
  <h2>New book</h2>

  <%= form_with model: book do |f| %>
    <h4>Title</h4>
      <%= f.text_field :title , class: "form-control book_title"%>
    <h4>Option</h4>
      <%= f.text_area :body , class: "form-control book_body"%>
    <%= f.submit 'Create Book', class: "btn btn-success" %>
  <% end %>

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %> error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<main>
<div class="container">
<div class="row">
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>Editing Book</h2>
<%= form_with model: @book do |f| %>
  <div class="form-group">
  <label for="inputTitle">Title</label><br>
  <%= f.text_field :title, autofocus: true, id:"inputTitle", placeholder:"タイトル", class: "form-control title"%>
  </div>
  
  <div class="form-group">
  <label for="inputOption">Option</label><br>
  <%= f.text_field :body, autofocus: true, id:"inputBody", placeholder:"Body", class: "form-control body"%>
  </div>
  
  <%= f.submit "Update Book", class: "btn btn-success" %>
  <p>
  <%= link_to "Show",book_path(@book.id) %>
   | 
  <%= link_to "Back",books_path %>
  </p>
<% end %>


</div>
</div>
</div>
</main>

app/views/books/index.html.erb
  <% if @book.errors.any? %>
  <%= @book.errors.count %> error prohibited this obj from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
  <% end %>
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
<%= render 'books/list', user: @user, book: @book %>
</div>

<div class="col-md-8 offset-md-1">
  <h2>Books</h2>
  <table class="table table-striped">
    <thead>
      <th></th>
      <th>Title</th>
      <th>Option</th>
      <th></th>
      <th></th>
    </thead>
    <tbody>
      <% @books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user.id) do %>
          <%= image_tag book.user.get_profile_image(50,50) %>
          <% end %>
          </td>
        <td>
        <%= link_to book_path(book.id) do %>
        <%= book.title %>
        <% end %>
        </td>
        <td><%= book.body %></td>
        <!--<td>ユーザーネーム：<%= book.user.name %></td>-->
        <td>
        <% if book.favorited_by?(current_user) %>
          
        <p>
        <%= link_to book_favorites_path(book), method: :delete do %>
          <i class="fas fa-heart"></i><%= book.favorites.count %>
        <% end %>
        </p>
        <% else %>
        <p>
        <%= link_to book_favorites_path(book), method: :post do %>
          <i class="far fa-heart"></i>
          <%= book.favorites.count %>
        <% end %>
        </p>
        
        <% end %>
        </td>
        <td>コメント数:<%= book.book_comments.count %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

</div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

  <%= form_with model: @book do |f| %>
    <h4>Title</h4>
      <%= f.text_field :title %>
    <h4>Option</h4>
      <%= f.text_area :body %>
    <%= f.submit 'Create Book' %>
  <% end %>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
<%= render 'list', user: @user, book: @book2 %>
</div>

<div class="col-md-8 offset-md-1">
  <h2>Book detail</h2>
  <table class="table table-striped">
  <tbody>
  <tr>
  <td><%= image_tag @book.user.get_profile_image(100,100) %><br><%= link_to @book.user.name, user_path(@book.user.id) %></td>
  <td><%= @book.title %></td>
  <td><%= @book.body %></td>
  <!--ユーザーネーム：<%= @book.user.name %>-->
  <!--投稿日：<%= @book.created_at.strftime('%Y/%m/%d') %>-->
  <% if @book.user == current_user %>
    <td><%= link_to "Edit", edit_book_path(@book.id) , class: "btn btn-success"%></td>
    <td><%= link_to "Destroy", book_path(@book), method: :delete , "data-confirm" => "本当に消しますか？", class: "btn btn-danger"%></td>
  <% end %>
  <td>
    <% if @book.favorited_by?(current_user) %>
    <p>
      <%= link_to book_favorites_path(@book), method: :delete do %>
        <i class="fas fa-heart"></i><%= @book.favorites.count %>
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to book_favorites_path(@book), method: :post do %>
        <i class="far fa-heart"></i><%= @book.favorites.count %>
      <% end %>
    </p>
  <% end %>
  </td>
  <td>コメント数:<%= @book.book_comments.count %></td>
  </tr>
  </tbody>
  </table>

<div>
  <table>
    <% @book.book_comments.each do |book_comment| %>
    <tr>
      <td>
        <%= image_tag book_comment.user.get_profile_image(100,100) %><br>
        <%= link_to book_comment.user.name,user_path(book_comment.user.id) %>
      </td>
      <td>
        <%= book_comment.comment %>
      </td>
      <td>
        <% if book_comment.user == current_user %>
          <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn btn-danger" %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </table>
</div>
<div>
  <%= form_with model: [@book, @book_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %><br>
    <%= f.submit "送信" %>
  <% end %>
</div>

</div>

</div>
</div>

app/views/homes/about.html.erb
<div class="container">
<div class="row">
<div class="px-3 mx-auto">
<h1>
    Welcome to 
    <i class="fas fa-book"></i>
    <strong>Bookers!</strong>
</h1>
</div>
</div>
</div>

app/views/homes/top.html.erb
<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
</head>

<main>
<div class="container">
<div class="row">
<div class="px-3 mx-auto">
<h1>
    Welcome to 
    <i class="fas fa-book"></i>
    <strong>Bookers!!</strong>
</h1>
<p>
    in
    <i class="fas fa-book"></i>
    <strong>Bookers</strong>
    ,
</p>
<p>
    you can share and exchange your opinions , inpressions , and emotions
</p>
<p>
    about various books!
</p>

<div class="btn-wrapper col-10 mx-auto">
<p>
    <%= link_to 'Log in', new_user_session_path, class: "btn btn-info btm-sm btn-block mb-3" %>
</p>
<p>
    <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-success btm-sm btn-block mb-3" %>
</p>
</div>

</div>
</div>
</div>

</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body class="d-flex flex-column vh-100">
    
    <header>
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark text-white">
    <div class="container">
      <span><%= link_to 'Bookers', root_path, class:"navbar-brand nav-link p-3 text-light" %></span>
    <div class="navbar-nav ml-auto">
    <% if user_signed_in? %>
        <%= link_to user_path(current_user.id), class:"nav-link p-3 text-light" do %>
        <i class="fas fa-home"></i>
        Home
        <% end %>
        <%= link_to users_path, class:"nav-link p-3 text-light" do %>
        <i class="fas fa-users"></i>
        Users
        <% end %>
        <%= link_to books_path, class:"nav-link p-3 text-light" do %>
        <i class="fas fa-book-open"></i>
        Books
        <% end %>
        <%= link_to destroy_user_session_path, method: :delete, class:"nav-link p-3 text-light" do %>
        <i class="fas fa-sign-out-alt"></i>
        logout
        <% end %>
        
    <% else %>
      <%= link_to root_path, class:"nav-link p-3 text-light color-white" do %>
      <i class="fas fa-home"></i>
      Home
      <% end %>
      <%= link_to about_path, class:"nav-link p-3 text-light color-white" do %>
      <i class="fas fa-link"></i>
      About
      <% end %>
      <%= link_to new_user_registration_path, class:"nav-link p-3 text-light color-white" do %>
      <i class="fas fa-user-plus"></i>
      sign up
      <% end %>
      <%= link_to new_user_session_path, class:"nav-link p-3 text-light color-white" do %>
      <i class="fas fa-sign-in-alt"></i>
      login
      <% end %>
    <% end %>
    </div>
    </div>
    </nav>
    </header>
  
  <main>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </main>
    
  <footer class="bg-white text-black pt-5 pb-4">
    <div class="container">
      <p class="mx-auto text-center">CopyRight Infratop.inc</p>
    </div>
  </footer>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <%= @user.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<main>

<div class="container">
<div class="row">
<div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>User info</h2>
<%= form_with model: @user do |f| %>
  <div class="form-group">
  <label for="inputName">Name</label><br>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前", class: "form-control name"%>
  </div>
  
  <div class="form-group">
  <label for="inputImage">Image</label><br>
  <%= f.file_field :profile_image, placeholder: "プロフィール画像", accept: "image/*" %> 
  </div>
  
  <div class="form-group">
  <label for="inputIntroduction">Introduce</label><br>
  <%= f.text_field :introduction, autofocus: true, id:"inputIntroduction", placeholder:"紹介文", class: "form-control introduction"%>
  </div>
  
  <%= f.submit "Update User", class: "btn btn-secondary" %>
<% end %>
</div>
</div>
</div>

</main>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
<%= render 'books/list', user: @user, book: @book %>
</div>

<div class="col-md-8 offset-md-1">
  <h2>Users</h2>
  <table class="table table-striped">
    <thead>
      <th>image</th>
      <th>name</th>
      <th></th>
    </thead>
    <tbody>
      <% @users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image(50,50) %></td>
        <td>
        <%= user.name %>
        </td>
        <td>
          <%= link_to user_path(user.id) do %>
          Show
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

</div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
<div class="row">
<div class="col-md-3">
  <%= render 'books/list', user: @user, book: @book %>
</div>


<div class="col-md-8 offset-md-1">
<h2>Books</h2>
<table class="table table-striped">
<thead>
  <th></th>
  <th>Title</th>
  <th>Option</th>
  <th></th>
  <th></th>
</thead>

<tbody>
<% @books.each do |book| %>
<tr>
  <td>
    <%= link_to user_path(book.user.id) do %>
    <%= image_tag book.user.get_profile_image(100,100) %>
    <% end %>
  </td>
  <td><%= link_to book.title , book_path(book.id)%></td>
  <td><%= book.body %></td>
  <!--ユーザーネーム：<%= book.user.name %>-->
  <td>
        <% if book.favorited_by?(current_user) %>
          
        <p>
        <%= link_to book_favorites_path(book), method: :delete do %>
          <i class="fas fa-heart"></i><%= book.favorites.count %>
        <% end %>
        </p>
        <% else %>
        <p>
        <%= link_to book_favorites_path(book), method: :post do %>
          <i class="far fa-heart"></i><%= book.favorites.count %>
        <% end %>
        </p>
        
        <% end %>
  </td>
  <td>コメント数:<%= book.book_comments.count %></td>
</tr>
<% end %>
</tbody>

</table>
</div>

</div>
</div>